### ISSUE TITLE
random fails with python 3.11

### ISSUE THREAD

**Issue by hariszaf** [ramellose/manta#13]
Hi!

In python 3.11 there are some [changes](https://docs.python.org/3/whatsnew/3.11.html#porting-to-python-3-11) in the `random` library that makes the [selection of an arbitrary node as root](https://github.com/ramellose/manta/blob/master/manta/flow.py#L380C5-L380C40) to fail. 

I could give it a shot for a workaround if you think this observation is valid.

**Comment by hariszaf** [comment]
in my case, those 2 commits seems to solve the issue.

**Comment by ramellose** [comment]
Thank you for your contribution! If you want, feel free to create a PR to the repo so you can be acknowledged as a contributor.
