### ISSUE TITLE
cluster_graph - unexpected keyword argument 'balance'

### ISSUE THREAD

**Issue by vmikk** [ramellose/manta#2]
Dear Dr. Röttjers,

Unfortunately the current version of manta (`manta-1.0.1.dev32`, 45cdc89c30c59826ddcfd7d64b623d516133b1cb) returns an error after the execution.
I've tried it with the demo example `manta -i demo -o filepath_to_output_network`.

Error message:
```
 File ".../manta/main.py", line 282, in main
    results = cluster_graph(network, limit=args['limit'], max_clusters=args['max'],
TypeError: cluster_graph() got an unexpected keyword argument 'balance'
```

Manta was installed with the following command:
`pip install git+https://github.com/ramellose/manta.git`

With best regards,
Vladimir

**Comment by ramellose** [comment]
Hi Vladimir, thank you for reporting the issue! Unfortunately, I forgot to remove a redundant parameter after my last commit. This has now been removed so manta should work again. Please let me know if you run into any other issues.
