### ISSUE TITLE
Just some doubts

### ISSUE THREAD

**Issue by FilipeMatteoli** [ramellose/manta#3]
I just read manta's paper and looks very promising. I am conducting microbiome network analysis in r, mainly using igraph. My intention was to stick into r until the end of the analysis but I noticed the lack of microbiome-specific module detection algorithms. Is there any way to use manta within r, or plans to do this in the feature?

If not maybe some tutorial on how to export an igraph object and run manta on it would help other users and increase manta usage as I believe most microbiome analysis is still performed using r.

Also, I was wondering if other igraph algorithms (e.g. cluster_louvain, used in https://www.nature.com/articles/s41467-020-17541-6, among others) are suitable to module detection in microbiome data. 

Best,

**Comment by ramellose** [comment]
Hi Filipe, thanks for your comments! At the moment, I have no plans to rewrite manta so it can be used in R. While the tool is written as Python, you access it via command line. It is possibe to include command line calls within R scripts though (https://stat.ethz.ch/R-manual/R-devel/library/base/html/system.html).  

Many of the formats that can be exported via igraph (https://igraph.org/r/doc/write_graph.html) are accepted by manta. After export to a format like graphml, the default tutorial can be followed. 

Louvain modularity clustering is definitely suitable, but its most commonly used implementation does not treat modularity as weighted, e.g. the optimization function optimizes for low number of edges outside clusters. Those inter-cluster edges can be either negatively- or positively-weighted edges. As a result, the widely available implementations are more suitable for networks with few negatively weighted edges. On networks with both types of edges, Louvain clusters with unweighted modularity are qualitatively different from manta clusters. 

I hope this answers your questions!
